#ifndef FALLGUARD_APP_CONFIG_H
#define FALLGUARD_APP_CONFIG_H

#include "driver/gpio.h"

#define MQTT_BROKER_HOST  "116.204.127.178"
#define MQTT_BROKER_PORT  1883
#define MQTT_DEVICE_ID    "DEV-MINI-001"
#define MQTT_USERNAME     "DEV-MINI-001"
#define MQTT_PASSWORD     "HvBABsArDz7L5XMqyMAXCD0sUzdZSu6m"

#define FALLGUARD_BUTTON_GPIO GPIO_NUM_0
#define FALLGUARD_LED_GPIO    GPIO_NUM_2
#define FALLGUARD_BUZZER_GPIO GPIO_NUM_39
#define FALLGUARD_BOOT_BEEP_MS 35

#define FALLGUARD_PARAM_QUERY_START_DELAY_MS 1000
#define FALLGUARD_PARAM_QUERY_RETRY_MS 3000
#define FALLGUARD_PARAM_QUERY_MAX_ATTEMPTS 5
#define FALLGUARD_RADAR_PROFILE_ACK_TIMEOUT_MS 3000
#define FALLGUARD_3D_ENABLE_DELAY_MS 10000
#define FALLGUARD_3D_DIAG_TIMEOUT_MS 5000
#define FALLGUARD_RADAR_HEIGHT_M 2.7f
#define FALLGUARD_RADAR_THRESHOLD_M 0.5f
#define FALLGUARD_RADAR_SENSITIVITY 30U
#define FALLGUARD_RADAR_ZONE_BOUNDARY_M 1.5f
#define FALLGUARD_ENABLE_USER_LOG 0
#define FALLGUARD_ENABLE_3D_CLOUD 0

#define BUTTON_EVENT_QUEUE_LEN 8

#endif /* FALLGUARD_APP_CONFIG_H */
